version: '3'
services:
  webapp:
    image: mcr.microsoft.com/dotnet/aspnet:7.0
    container_name: catalog.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - 'DatabaseSettings:ConnectionString=mongodb://admin:admin@catalogdb:27017'
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile
    ports:
      - '8000:80'
    depends_on:
      - catalogdb
        
  mongoclient:
    image: mongoclient/mongoclient
    container_name: mongoclient
    environment:
      MONGOCLIENT_DEFAULT_CONNECTION_URL: mongodb://admin:admin@catalogdb:27017
    ports:
      - "3100:3000"
    depends_on:
      - catalogdb

  catalogdb:
    image: mongo:latest
    container_name: shopping-mongo
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - mongodb-data:/data/db
    # Optional: Uncomment the lines below if you have initialization scripts
    # volumes:
    #   - ./init-scripts:/docker-entrypoint-initdb.d
    # Optional: Uncomment the lines below if you have a custom entrypoint script
    # command: ["--auth"]

volumes:
  mongodb-data:
